# Generated by Django 2.2.13 on 2022-01-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_userprofile_can_add_parliament_details'),
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Suggestion', to='authentication.UserProfile')),
                ('voters', models.ManyToManyField(to='authentication.UserProfile')),
            ],
        ),
    ]
