# Generated by Django 2.2.13 on 2022-01-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0002_parliamentsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parliamentsuggestion',
            name='voters',
            field=models.ManyToManyField(blank=True, to='authentication.UserProfile'),
        ),
    ]
