# Generated by Django 2.2.6 on 2020-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200211_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='github_image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
