# Generated by Django 2.2.6 on 2020-04-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20200211_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
