# Generated by Django 2.2.6 on 2020-04-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20200405_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.Role'),
        ),
    ]
