# Generated by Django 2.2.13 on 2022-01-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='extracharges',
            new_name='extra_charges',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='monthlybills',
            new_name='monthly_bill',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='totalbill',
            new_name='total_bill',
        ),
    ]
