# Generated by Django 2.2.13 on 2022-02-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0005_auto_20220123_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mess',
            options={'verbose_name_plural': 'messes'},
        ),
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
    ]
