# Generated by Django 3.2.9 on 2021-12-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='date',
            field=models.DateField(),
        ),
    ]
