# Generated by Django 3.2.9 on 2021-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200303_2140'),
        ('noticeboard', '0002_alter_noticeboard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='voters',
            field=models.ManyToManyField(blank=True, to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
