# Generated by Django 3.2.9 on 2021-12-14 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticeboard', '0003_auto_20211214_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
