# Generated by Django 2.2.6 on 2019-10-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roll_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_joining',
            field=models.CharField(max_length=4),
        ),
    ]
