# Generated by Django 2.2.6 on 2019-10-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191009_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roll_number',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_joining',
            field=models.CharField(max_length=10),
        ),
    ]
