# Generated by Django 2.2.6 on 2019-10-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userprofile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
