# Generated by Django 2.2.6 on 2020-02-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_userprofile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
