# Generated by Django 2.2.6 on 2020-02-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
