# Generated by Django 2.2.13 on 2021-12-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200303_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_post_notice',
            field=models.BooleanField(default=False),
        ),
    ]
