# Generated by Django 2.2.13 on 2022-01-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_userprofile_can_post_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add_parliament_details',
            field=models.BooleanField(default=False),
        ),
    ]
