# Generated by Django 2.2.13 on 2022-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_userprofile_can_add_parliament_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mess_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roll_number',
            field=models.IntegerField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
