# Generated by Django 2.2.13 on 2022-01-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20220123_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='roll_number',
        ),
    ]
