# Generated by Django 2.2.13 on 2022-02-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_userprofile_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mess_id',
        ),
    ]
