# Generated by Django 2.2.6 on 2019-10-10 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_auto_20191009_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('joint_secy1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_secy1', to='authentication.UserProfile')),
                ('joint_secy2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_secy2', to='authentication.UserProfile')),
                ('secy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.UserProfile')),
            ],
        ),
    ]
