# Generated by Django 2.2.6 on 2019-10-10 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20191009_1206'),
        ('workshop', '0002_auto_20191010_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='joint_secy',
            field=models.ManyToManyField(blank=True, related_name='councils_joint_secy', to='authentication.UserProfile'),
        ),
        migrations.RemoveField(
            model_name='council',
            name='secy',
        ),
        migrations.AddField(
            model_name='council',
            name='secy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='councils_secy', to='authentication.UserProfile'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Council')),
                ('joint_secy', models.ManyToManyField(blank=True, related_name='clubs_joint_secy', to='authentication.UserProfile')),
                ('secy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_secy', to='authentication.UserProfile')),
            ],
        ),
    ]
