# Generated by Django 2.2.6 on 2019-10-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20191010_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='start_time',
        ),
        migrations.AddField(
            model_name='workshop',
            name='audience',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
