# Generated by Django 2.2.6 on 2019-10-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20191010_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='audience',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
