# Generated by Django 2.2.6 on 2019-10-10 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_auto_20191010_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='joint_secy',
            field=models.ManyToManyField(blank=True, related_name='is_joint_secy_club', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='club',
            name='secy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_secy_club', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='council',
            name='joint_secy',
            field=models.ManyToManyField(blank=True, related_name='is_joint_secy_council', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='council',
            name='secy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_secy_council', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='is_contact_workshop', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(default='2019-10-10'),
            preserve_default=False,
        ),
    ]
