# Generated by Django 2.2.6 on 2019-10-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20191010_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='joint_secy',
            field=models.ManyToManyField(blank=True, related_name='club_joint_secy', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='club',
            name='secy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_secy', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='council',
            name='joint_secy',
            field=models.ManyToManyField(blank=True, related_name='council_joint_secy', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='council',
            name='secy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_secy', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='workshop_contact', to='authentication.UserProfile'),
        ),
    ]
