# Generated by Django 2.2.6 on 2020-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_userprofile_is_admin'),
        ('workshop', '0009_auto_20191021_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='authentication.UserProfile'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_workshops', to='authentication.UserProfile'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='organized_workshops', to='authentication.UserProfile'),
        ),
    ]
