# Generated by Django 2.2.6 on 2020-03-03 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200303_2140'),
        ('workshop', '0011_auto_20200211_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='gensec',
        ),
        migrations.RemoveField(
            model_name='council',
            name='joint_gensec',
        ),
        migrations.AddField(
            model_name='club',
            name='large_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='small_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='joint_secy',
            field=models.ManyToManyField(blank=True, related_name='council_joint_secy', to='authentication.UserProfile'),
        ),
        migrations.AddField(
            model_name='council',
            name='large_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='secy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_secy', to='authentication.UserProfile'),
        ),
        migrations.AddField(
            model_name='council',
            name='small_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
