# Generated by Django 2.2.6 on 2020-03-03 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200303_2140'),
        ('workshop', '0012_auto_20200303_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='joint_secy',
        ),
        migrations.RemoveField(
            model_name='council',
            name='secy',
        ),
        migrations.AddField(
            model_name='council',
            name='gensec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_gensec', to='authentication.UserProfile', verbose_name='General Secretary'),
        ),
        migrations.AddField(
            model_name='council',
            name='joint_gensec',
            field=models.ManyToManyField(blank=True, related_name='council_joint_gensec', to='authentication.UserProfile', verbose_name='Joint General Secretary'),
        ),
    ]
