# Generated by Django 2.2.6 on 2020-04-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200303_2140'),
        ('workshop', '0013_auto_20200303_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='attendees',
        ),
        migrations.AddField(
            model_name='workshop',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='interested_workshops', to='authentication.UserProfile'),
        ),
    ]
