# Generated by Django 2.2.6 on 2020-05-03 04:26

from django.db import migrations, models
import django.db.models.deletion
import workshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0015_auto_20200503_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[workshop.models.validate_kebab_case])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='workshop.Club')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tagged_workshops', to='workshop.Tag'),
        ),
    ]
