# Generated by Django 2.2.6 on 2020-05-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_auto_20200503_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='tag',
            new_name='tags',
        ),
    ]
