# Generated by Django 2.2.10 on 2020-05-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0019_auto_20200503_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='resources',
        ),
        migrations.AddField(
            model_name='workshop',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkshopResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('resource_type', models.CharField(choices=[('Prerequisite', 'Prerequisite'), ('Material', 'Material')], max_length=20)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='workshop.Workshop')),
            ],
        ),
    ]
