# Generated by Django 2.2.10 on 2020-11-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200303_2140'),
        ('workshop', '0023_auto_20201120_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='joint_secy',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='secy',
        ),
        migrations.AddField(
            model_name='entity',
            name='point_of_contact',
            field=models.ManyToManyField(blank=True, related_name='entity_point_of_contact', to='authentication.UserProfile', verbose_name='Point of Contact'),
        ),
    ]
