# Generated by Django 2.2.10 on 2020-11-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0025_auto_20201121_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_workshop',
            field=models.BooleanField(default=True),
        ),
    ]
