# Generated by Django 2.2.13 on 2020-12-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0030_auto_20201222_2359'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['date', 'time'], name='workshop_wo_date_62849f_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['-date', '-time'], name='workshop_wo_date_9e5d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['club', '-date'], name='workshop_wo_club_id_e6cf8a_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['club', 'date'], name='workshop_wo_club_id_00d260_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['title'], name='workshop_wo_title_6c4bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['location'], name='workshop_wo_locatio_f39255_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['audience'], name='workshop_wo_audienc_ce053f_idx'),
        ),
    ]
