# Generated by Django 2.2.10 on 2021-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_added_academic_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profsandhods',
            name='department',
            field=models.CharField(choices=[('bce', 'Biochemical Engineering'), ('bme', 'Biomedical Engineering'), ('cer', 'Ceramic Engineering'), ('che', 'Chemical Engineering'), ('chy', 'Chemistry'), ('civ', 'Civil Engineering'), ('cse', 'Computer Science and Engineering'), ('ece', 'Electronics Engineering'), ('eee', 'Electrical Engineering'), ('mat', 'Mathematics and Computing'), ('mec', 'Mechanical Engineering'), ('met', 'Metallurgical Engineering'), ('min', 'Mining Engineering'), ('mst', 'Materials Science and Technology'), ('phe', 'Pharmaceutical Engineering and Technology'), ('phy', 'Physics'), ('hss', 'Humanistic Studies')], max_length=60),
        ),
    ]
