# Generated by Django 2.2.13 on 2021-12-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20211206_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proffsandhods',
            options={'verbose_name': 'Proffs and HODs', 'verbose_name_plural': 'Proffs and HODs'},
        ),
        migrations.AlterModelOptions(
            name='studymaterials',
            options={'verbose_name_plural': 'Study Materials'},
        ),
        migrations.RemoveField(
            model_name='proffsandhods',
            name='year_of_joining',
        ),
        migrations.AddField(
            model_name='proffsandhods',
            name='proffs_and_HODs',
            field=models.URLField(default='https://www.iitbhu.ac.in/dept'),
        ),
        migrations.AlterModelTable(
            name='proffsandhods',
            table=None,
        ),
    ]
