name: Lint Checks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: pipenv install
      - name: Run lint checks
        run: pipenv run pylint --load-plugins pylint_django team workshops workshop authentication config academics noticeboard
