name: Lint Checks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install
      - name: Run lint checks
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run pylint --load-plugins pylint_django team workshops workshop authentication
